### ISSUE TITLE
Deploy Key vault to Azure

### ISSUE THREAD

**Issue by jonasanker** [AnalogIO/azure#7]
1. Expand azuredeploy.bicep file to also deploy an Azure Key vault
2. Use the most minimal configuration - Google what that is

Links
[Microsoft.KeyVault vaults](https://learn.microsoft.com/en-us/azure/templates/microsoft.keyvault/vaults?pivots=deployment-language-bicep)

**Comment by duckth** [comment]
I have opened a (currently draft) pull request for this on https://github.com/AnalogIO/infrastructurepoc/pull/11

I had some trouble with the access policy of the vault - right now it just uses my own objectId for testing.
We should probably be able to use a group for this? I didn't seem to have access to that on Azure however, so wasn't sure where to go with it
